### 회원 승인 시 권한 설정
POST http://localhost:8003/api/user/userRole
Content-Type: application/json

{
  "userId": "admin",
  "roleId": 3
}

### userId로 권한 목록 조회
GET http://localhost:8003/api/user/userRole/list?userId=hozzik
Accept: application/json

### roleId로 userId 목록 조회
GET http://localhost:8003/api/user/userRole/list/roleId/1
Accept: application/json

### 회원 권한 수정
PUT http://localhost:8003/api/user/userRole
Content-Type: application/json

{
  "userId": "admin",
  "roleId": 2
}

### 회원 권한 삭제
DELETE http://localhost:8003/api/user/userRole/4
Accept: application/json



