POST http://localhost:8003/api/user/signup
Content-Type: application/json

{
  "userId": "www980304",
  "userPassword": "1234567890",
  "userName": "배범익",
  "userEmail": "www980304@gmail.com",
  "userRoles": [
    {"userRoleId": 1}
  ]
}

###
GET http://localhost:8003/api/user/login
X-USER-ID: user1
Accept: application/json

###
GET http://localhost:8003/api/user/profile
X-USER-ID: user2
Accept: application/json

###
PATCH http://localhost:8003/api/user/profile
X-USER-ID: user3
Content-Type: application/json

{
  "userName": "",
  "userEmail": "user@naver.com"
}

###
PATCH http://localhost:8003/api/user/profile/password
X-USER-ID: user1
Content-Type: application/json

{
  "userPassword": "432112312312"
}

###
DELETE http://localhost:8003/api/user/inactive
X-USER-ID: user2
Accept: application/json

###
PATCH http://localhost:8003/api/user/activate
X-USER-ID: user2
Accept: application/json

###
POST http://localhost:8003/api/role
Content-Type: application/json

{
  "roleInfo": "ROLE_ADMIN"
}

###
GET http://localhost:8003/api/role
Accept: application/json

###
DELETE http://localhost:8003/api/role/6
Accept: application/json

###
PUT http://localhost:8003/api/role/1
Content-Type: application/json

{
  "roleInfo": "ROLE_USER"
}