logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE

spring:
  application:
    name: user-service

  profiles:
    active: dev

  lifecycle:
    timeout-per-shutdown-phase: 30s

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  port: 8200
  shutdown: graceful
  servlet:
    encoding:
      force: true
      charset: UTF-8