logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE

spring:
  application:
    name: user-service

  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  shutdown: graceful
  servlet:
    encoding:
      force: true
      charset: UTF-8
  port: 8003

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8004/eureka/



