spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb;MODE=MYSQL
    username: sa
    password:
    type: org.apache.commons.dbcp2.BasicDataSource


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8004/eureka/