### 출석 조회
GET http://localhost:8003/api/user/attendance/list/2024/05
X-USER-ID: hihi
Accept: application/json

### 출석 체크
POST http://localhost:8003/api/user/attendance
X-USER-ID: hihi
Content-Type: application/json
