### 출석 조회
GET http://localhost:8003/api/user/attendance/list
X-USER-ID: user
Accept: application/json

### 출석 체크
POST http://localhost:8003/api/user/attendance
X-USER-ID: user
Content-Type: application/json
