### 훅 생성
POST http://localhost:8003/api/user/hook
X-USER-ID: haha2
Content-Type: application/json

{
  "hookTypeId": 1,
  "hookUrl": "https://hook.dooray.com/services/3204376758577275363/3803821072241404116/Ebqy-Mh-Qm6bXusR9ZTtMQ"
}

### 훅 조회
GET http://localhost:8003/api/user/hook
X-USER-ID: haha
Accept: application/json

### 훅 수정
PUT http://localhost:8003/api/user/hook
X-USER-ID: haha
Content-Type: application/json

{
  "hookTypeId": 2,
  "hookUrl": "www"
}

### 훅 삭제
DELETE http://localhost:8003/api/user/hook
X-USER-ID: haha
Accept: application/json

### 전체 회원 훅 URL 조회
GET http://localhost:8003/api/user/hook/list/1
Accept: application/json