### 회원 승인 대기 목록 조회
GET http://localhost:8003/api/user/waitingUserList?page=0&size=5
Accept: application/json

### 회원 승인 처리
PUT http://localhost:8003/api/user/approve
Content-Type: application/json

{
  "userId": "user1",
  "roleIds": [1, 2]
}

### 회원 승인 거절
DELETE localhost:8003/api/user/reject/user10
Accept: application/json